### ISSUE TITLE
能否创建一个DOCKER 容器

### ISSUE THREAD

**Issue by Guoc0529** [Unsigned-Long/River#2]
在编译ctrij的时候，ceres2.2.0的版本无法安装，一直报错
如果有一个docker 就完美了

**Comment by Unsigned-Long** [comment]
Be patient, bro.

**Comment by Guoc0529** [comment]
Brother, I've encountered another problem now.
fatal error: spdlog/stopwatch.h: No such file or directory
   11 | #include "spdlog/stopwatch.h"
      |          ^~~~~~~~~~~~~~~~~~~~
I had installed libspdlog

**Comment by Unsigned-Long** [comment]
Please make sure your **spdlog** version is at least **1.8.0 or higher** (if the origin source (using **apt-get**) does not support such a version, **download spdlog from GitHub** and compile it, install it). This way, you can easily measure the execution time of your code blocks!

**Comment by Guoc0529** [comment]
Brother, there's a new problem again！！
CMake Error at /home/guo/river/build/sbg_ros_driver/cmake/sbg_driver-genmsg.cmake:343 (add_custom_target):
  add_custom_target cannot create target "sbg_driver_generate_messages_cpp"
  because another target with the same name already exists.  The existing
  target is a custom target created in source directory
  "/home/guo/river/src/river".  See documentation for policy CMP0002 for more
  details.
Call Stack (most recent call first):
  /opt/ros/noetic/share/genmsg/cmake/genmsg-extras.cmake:307 (include)
  sbg_ros_driver/CMakeLists.txt:55 (generate_messages)
tks！！！！

**Comment by Guoc0529** [comment]
if  catkin_make -DCATKIN_WHITELIST_PACKAGES="river" 
/usr/bin/ld: CMakeFiles/river_prog.dir/exe/main.cpp.o: in function `unsigned long long fmt::v8::detail::width_checker<fmt::v8::detail::error_handler>::operator()<float, 0>(float) [clone .isra.0]':
main.cpp:(.text+0x7e): undefined reference to `fmt::v8::detail::error_handler::on_error(char const*)'
/usr/bin/ld: CMakeFiles/river_prog.dir/exe/main.cpp.o: in function `unsigned long long fmt::v8::detail::precision_checker<fmt::v8::detail::error_handler>::operator()<float, 0>(float) [clone .isra.0]':
main.cpp:(.text+0x9e): undefined reference to `fmt::v8::detail::error_handler::on_error(char const*)'
/usr/bin/ld: CMakeFiles/river_prog.dir/exe/main.cpp.o: in function `fmt::v8::basic_format_context<fmt::v8::appender, char>::on_error(char const*) [clone .isra.0]':
