### ISSUE TITLE
What kind of Radar in your work?

### ISSUE THREAD

**Issue by KJ-Falloutlast** [Unsigned-Long/River#4]
It's great that you guys are open sourcing your excellent work, I was wondering what type of Radar you are using?

**Comment by Unsigned-Long** [comment]
Thanks for your support :smiley:. The radar employed in `River` is the mm-wave radar: **TI AWR1843 (AWR1843BOOST)**.
![eqp3](https://github.com/Unsigned-Long/River/assets/76953144/2cdcc3e8-d2d0-4771-8af8-fa5076f2beb4)
